# Generated by Django 3.1 on 2021-01-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('birthday', models.DateField(verbose_name='Data de Nascimento')),
                ('date_register', models.DateTimeField(auto_now_add=True, verbose_name='Data de Nascimento')),
            ],
        ),
    ]
